### ISSUE TITLE
ATC Online API fails with extended coverage

### ISSUE THREAD

**Issue by Kahn** [vatpac-technology/vatsim-map#7]
https://map.vatpac.org/v1/atc/online doesn't respond when a sector is being extended

**Comment by zachbf** [comment]
fixed in https://github.com/vatpac-technology/vatsim-map/tree/38a8f8cf4725cfa4908be14f17e9bbff47d1ca57

**Comment by zachbf** [comment]
additional fix in eae2406315f7a736fff4a98e4db59fde072c5198
